### ISSUE TITLE
Allow crest to use ALPB solvent model

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/crest#18] opened 2020-10-23 10:03 UTC
**Is your feature request related to a problem? Please describe.**
Given that the ALPB solvent model is the default solvent model in xtb 6.3.3. It might be useful to update the crest such that it will use ALPB solvent model as well.

**Describe the solution you'd like**
Allow crest to use the -alpb flag or deprecate the -gbsa/-g flag and replace it with alpb.

**Comment by awvwgk** [comment] 2020-10-23 13:11
Duplicate of #12

**Closed** 2020-11-05 11:29 UTC
Labels: duplicate
