### ISSUE TITLE
CREST on macOS M1

### ISSUE THREAD

**Issue by avasyanin** [grimme-lab/crest#73] opened 2021-09-02 05:23 UTC
Is it possible to build CREST on the macOS M1? Looks like some issues with MKL/OpenBLAS cannot be resolved automatically:

`env LDFLAGS="-L/opt/homebrew/opt/openblas/lib" CC=gcc-11 FC=gfortran-11 meson setup _build_gcc --prefix=$PWD/_dist -Dla_backend=openblas

The Meson build system
Version: 0.59.1
Source dir: /Users/alex/src/crest-2.11.1
Build dir: /Users/alex/src/crest-2.11.1/_build_gcc
Build type: native build
Project name: crest
Project version: 2.11.0
Fortran compiler for the host machine: gfortran-11 (gcc 11.1.0 "GNU Fortran (Homebrew GCC 11.2.0) 11.1.0")
Fortran linker for the host machine: gfortran-11 ld64 650.9
C compiler for the host machine: gcc-11 (gcc 11.1.0 "gcc-11 (Homebrew GCC 11.2.0) 11.1.0")
C linker for the host machine: gcc-11 ld64 650.9
Host machine cpu family: aarch64
Host machine cpu: arm64
Run-time dependency OpenMP found: YES 4.5
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Found CMake: /opt/homebrew/bin/cmake (3.21.2)
Run-time dependency openblas found: NO (tried pkgconfig and framework)
Library openblas found: YES
config/meson.build:100: WARNING: Passed invalid keyword argument "exe_deps".
WARNING: This will become a hard error in the future.
Run-time dependency lapack found: YES
Program asciidoctor found: YES (/opt/homebrew/bin/asciidoctor)
Configuring crest.1 with command
Build targets in project: 1

Found ninja-1.10.2 at /Users/alex/miniforge3/envs/py39/bin/ninja`

And following install command finishes with an error:

`meson install -C _build_gc
<...>
gfortran-11  -o crest crest.p/src_acidbase.f90.o crest.p/src_atmasses.f90.o crest.p/src_axis3.f.o crest.p/src_biasmerge.f90.o crest.p/src_bondconstraint.f90.o crest.p/src_ccegen.f90.o crest.p/src_classes.f90.o crest.p/src_cleanup.f90.o crest.p/src_compress.f90.o crest.p/src_confcross.f90.o crest.p/src_confopt.f90.o crest.p/src_confparse.f90.o crest.p/src_confscript1.f90.o crest.p/src_confscript2_main.f90.o crest.p/src_confscript2_misc.f90.o crest.p/src_confscript3.f90.o crest.p/src_constraining.f90.o crest.p/src_cregen.f90.o crest.p/src_data.f90.o crest.p/src_deprotonate.f90.o crest.p/src_dft_propcalc.f90.o crest.p/src_drsp.f.o crest.p/src_ensemblecomp.f90.o crest.p/src_entropic.f90.o crest.p/src_entropy.f90.o crest.p/src_eval_timer.f90.o crest.p/src_filemod.f90.o crest.p/src_flexi.f90.o crest.p/src_floydwarshall.f90.o crest.p/src_freqmasses.f90.o crest.p/src_geo.f90.o crest.p/src_identifiers.f90.o crest.p/src_intmodes.f.o crest.p/src_io.f.o crest.p/src_iomod.F90.o crest.p/src_ligands.f90.o crest.p/src_ls_rmsd.f90.o crest.p/src_marqfit.f.o crest.p/src_minitools.f90.o crest.p/src_msmod.f90.o crest.p/src_msreact.f90.o crest.p/src_ncigeo.f90.o crest.p/src_neighbor.f.o crest.p/src_newcregen.f90.o crest.p/src_normmd.f90.o crest.p/src_ompmklset.f90.o crest.p/src_optinplace.f90.o crest.p/src_pka.f90.o crest.p/src_printouts.f90.o crest.p/src_prmat.f.o crest.p/src_progressbar.f90.o crest.p/src_propcalc.f90.o crest.p/src_protonate.f90.o crest.p/src_quicksort.f90.o crest.p/src_reactor.f90.o crest.p/src_readl2.f.o crest.p/src_readl.f.o crest.p/src_relaxensemble.f90.o crest.p/src_rotcompare.f90.o crest.p/src_scratch.f90.o crest.p/src_sdfio.f90.o crest.p/src_select.f90.o crest.p/src_setdg.f90.o crest.p/src_shortpath.f90.o crest.p/src_signal.c.o crest.p/src_sigterm.f90.o crest.p/src_solve.f.o crest.p/src_solvtool.f90.o crest.p/src_sortens.f90.o crest.p/src_spline.f90.o crest.p/src_stereoisomers.f90.o crest.p/src_strucreader.f90.o crest.p/src_symmetry2.f90.o crest.p/src_symmetry_i.c.o crest.p/src_syscheck.f90.o crest.p/src_tautomerize.f90.o crest.p/src_thermocalc.f90.o crest.p/src_thermo.f90.o crest.p/src_trackorigin.f90.o crest.p/src_trialmd.f90.o crest.p/src_utilities.f.o crest.p/src_xtbmodef.f90.o crest.p/src_zdata.f90.o crest.p/src_zfunctional.f90.o crest.p/src_zsort.f90.o crest.p/src_ztopology.f90.o crest.p/src_crest_main.f90.o -L/opt/homebrew/opt/openblas/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -fopenmp -lopenblas -ldl -lm /Users/alex/miniforge3/envs/py39/lib/libopenblas.dylib -lgfortran
Undefined symbols for architecture arm64:
  "_mkl_scoomm_", referenced from:
      _intens_ in src_solve.f.o
  "_mkl_set_num_threads_", referenced from:
      _ompautoset_ in src_ompmklset.f90.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Could not rebuild /Users/alex/src/crest-2.11.1/_build_gcc`

**Comment by awvwgk** [comment] 2021-09-03 17:30
Crest currently depends on a couple of functionalities that are only provided with Intel's MKL implementation of BLAS/LAPACK.

Unless there is a port of MKL for OSX/aarch64, you can't compile CREST on this architecture.

**Comment by ghutchis** [comment] 2021-11-02 19:58
While the `crest-feedstock` now supplies `crest` for `osx-arm64` it's not working yet. (It seems to start the `xtb` optimization, then fails .. although `xtb` optimization works manually.)

Should I file a separate issue for that?

**Comment by awvwgk** [comment] 2021-11-02 20:24
Best to report this issue at the [feedstock repository](https://github.com/conda-forge/crest-feedstock) including the full information from `conda list` and `conda info`.

**Comment by awvwgk** [comment] 2021-11-03 08:20
@ghutchis I don't have access to a Mac, therefore I can't help much here. In case you have access to this platform, please try building CREST natively to see whether there is a fundamental issue with CREST or whether there is an issue with the cross-compiled binary from conda-forge.

**Comment by ghutchis** [comment] 2021-11-05 15:55
Unfortunately, I'm hitting some weird environment clashes when building locally. I'll sort that, but it may take a few days.

**Comment by kjelljorner** [comment] 2021-11-06 18:59
I get the same error as @ghutchis that CREST crashed on the initial xtb optimization step, while running the same input with xtb doesn't produce any errors. Installed the code from pull request #78 to allow installation with openblas. Running crest with `-noopt` works.

**Comment by ghutchis** [comment] 2021-11-06 21:54
@kjelljorner - are you using the x64 binary or did you install the native `osx-arch64` binary? 

I'm hitting the problem with the native binary, but maybe it's just a general Mac issue.

**Comment by awvwgk** [comment] 2021-11-06 21:59
Thanks for checking, unfortunately with the provided information so far I won't be help to help much here. If you have time, please consider providing a full bug report containing all the relevant information.

If you have used a conda environment, please provide the full output from `conda info` and `conda list`. Otherwise please provide the build log (I need the compiler version, the commit built, ...). Finally, the actual input (full command line) and the output showing the error will be required.

I'm happy to help, but you have to give me at least something to work with.

**Comment by kjelljorner** [comment] 2021-11-07 01:18
Ok, I think I have something to go with. It seems to be an xtb problem, possibly related to macOS Monterey (@ghutchis might confirm this). Running the following example with xtb-6.4.1 from conda-forge produces what appears to be a "successful" optimization with xtb, but the output in `xtb.out` seems to be truncated. I did some rudimentary debugging with CREST and it seems that the error appears exactly on this line

https://github.com/grimme-lab/crest/blob/726ead1984688add3f8cf6089929f280cf18a6eb/src/confscript2_misc.f90#L178

[coord.zip](https://github.com/grimme-lab/crest/files/7491525/coord.zip)

**Comment by awvwgk** [comment] 2021-11-07 09:28
There don't seem to be an error in the `xtb` run, since we are “stopping” after the geometry summary but the optimized geometry is still printed, which should also produce a message in the standard output before it is written.

**Comment by kjelljorner** [comment] 2021-11-09 20:08
The situation is quite strange on my end. If I do `xtb tmpcoord > xtb.out`, the output is truncated. If I do `xtb tmpcoord | tee xtb.out` it is not. Not sure what could cause this type of behavior. I can however confirm that the truncated xtb output is the source of the error, as CREST crashes when it cannot find the line confirming the printing of the optimized geometry. https://github.com/grimme-lab/crest/blob/726ead1984688add3f8cf6089929f280cf18a6eb/src/confscript2_misc.f90#L180

**Comment by clavigne** [comment] 2021-11-09 21:26
After some troubleshooting, we identified that the problem has to do with gfortran buffering the IO. Setting `GFORTRAN_UNBUFFERED_ALL=1` at runtime solves the issue. [Details here](https://gcc.gnu.org/onlinedocs/gfortran/GFORTRAN_005fUNBUFFERED_005fALL.html).

Still investigating what causes the buffering to break.

**Comment by awvwgk** [comment] 2021-11-09 21:38
I think we didn't really explore the combination of crest and xtb with GFortran so far, since Intel is our main compiler, which we (for somewhat obvious reasons) can't use for OSX/ARM64 ;). If `GFORTRAN_UNBUFFERED_ALL` is what is needed to fix the issue, we could have crest just set this environment variable by default when spawning xtb subprocesses.

**Comment by kjelljorner** [comment] 2021-11-09 21:50
The problem occurs also for running xtb standalone that has been compiled with GFortran, which I would guess are all conda-forge builds. Therefore I think that setting this variable in crest is only a partial solution. I experienced the problem also under Rosetta 2 emulation, so it might be a wider problem for Macs in general, regardless of M1 or Intel. For now I devised the workaround to just define aliases for crest and xtb like this `alias xtb="GFORTRAN_UNBUFFERED_ALL=1 xtb"`. I would guess that this is related to the new macOS 12 Monterey is some way, but it is very difficult to find any information about what they might have changed.

**Comment by awvwgk** [comment] 2021-11-09 22:04
I haven't observed this behaviur on Linux with GCC 11 so far. This could be an issue in GFortran (or GCC) specific to MacOS, truncation of buffered IO looks like an actual bug to me, the GCC/GFortran developers might appreciate a bug report in case we can create a minimal reproducer.

**Comment by kjelljorner** [comment] 2021-11-10 01:47
This is a minimal example that displays the buffering problem for me using GFortran 11.1.0 on MacOS 12.0.1. It works as expected with LFortran 0.14, the only other free Fortran compiler for MacOS arm64. I also tried using `output_unit` from `iso_fortran_env` but it doesn't make any difference. Maybe @ghutchis or @fxcoudert could confirm?

```fortran
program name
  implicit none
  integer :: i 
  
  do i = 1, 10
    write(*,*) i
  end do
  
end program name
```

**Comment by kjelljorner** [comment] 2021-11-10 14:09
Seems that I did a bit of poor search for bug reports for GFortran. Found the right page, and there is already a bug reported which seems to indicate a problem with MacOS 12. Current strategy from GFortran seems to be to wait for a fix in the next update of MacOS. Seems that ifort is not affected what I can see from my tests.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102992

**Comment by fxcoudert** [comment] 2021-11-12 11:59
I can confirm that this is indeed the bug reported at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102992
The root cause is a bug in macOS 12.0.1: even executables that were compiled on earlier macOS versions, and worked fined on earlier macOS versions, fail with Monterey.

So this will indeed have to be fixed by Apple in a macOS update, to restore compatibility with earlier versions. However, there is also a workaround that is in the works for GCC, to switch to another mechanism for flushing I/O at end of execution: that patch is at https://gcc.gnu.org/pipermail/gcc-patches/2021-November/583445.html

In the meantime, the only workaround that I am aware of is setting `GFORTRAN_UNBUFFERED_ALL=1` in the environment.

**Comment by quadir7719** [comment] 2021-11-18 20:35
@fxcoudert 
Will setting GFORTRAN_UNBUFFERED_ALL=1 in the environment work ??
Can you tell me more?? I mean how I can go with it?

**Comment by awvwgk** [comment] 2021-11-18 20:37
Exporting the environment variable in your current shell with

```
export GFORTRAN_UNBUFFERED_ALL=1
```

or adding the above line to your `~/.bashrc` or `~/.zshrc` should work.

**Comment by ghutchis** [comment] 2021-11-18 20:39
Can confirm. Since this affects more than just `crest`, it's a good suggestion to add to `~/.bashrc` or `~/.zshrc` etc.

**Comment by awvwgk** [comment] 2021-11-18 20:42
Indeed, this affects a lot more than Fortran projects than `xtb` and `crest`. There is now also a thread on the Fortran-lang discourse on this topic:

https://fortran-lang.discourse.group/t/gfortran-code-is-not-proving-data-in-output-file-macos-monterey/2297

**Comment by quadir7719** [comment] 2021-11-19 06:18
@ghutchis see I am working in the complex system and computational physics area. For me, it's very important. If I am not able to write output in the data files in previous methods, then I have to switch my machines. I have to tackle lots of terminal output and file output.

**Comment by quadir7719** [comment] 2021-11-19 06:48
> export GFORTRAN_UNBUFFERED_ALL=1

I export it to my ~/.bashrc file but it is the same. No effect.

**Comment by ghutchis** [comment] 2021-11-19 16:03
If you have not run it in your current Terminal windows, adding it to your shell (.bashrc or .zshrc) will not have an effect until you open a new session.

**Comment by quadir7719** [comment] 2021-11-20 08:22
@ghutchis, GFORTRAN_UNBUFFERED_ALL is worked but  with ~/.zshrc

**Closed** 2021-11-25 13:43 UTC
